### ISSUE TITLE
Error: invalid signature while downloading stylua binary

### ISSUE THREAD

**Issue by Tolomeo** [xiyaowong/coc-stylua#2]
Trying to download `stylua` fails with the following error:

```
[coc.nvim]: Uncaught exception: Unhandled error. (Error: invalid signature: 0x4f44213c
    at /Users/diegof/.config/coc/extensions/node_modules/coc-stylua/lib/index.js:8130:29
    at tryCatcher (/Users/diegof/.config/coc/extensions/node_modules/coc-stylua/lib/index.js:1324:21)
    at Promise2._settlePromiseFromHandler (/Users/diegof/.config/coc/extensions/node_modules/coc-stylua/lib/index.js:5788:32)
    at Promise2._settlePromise (/Users/diegof/.config/coc/extensions/node_modules/coc-stylua/lib/index.js:5842:16)
    at Promise2._settlePromise0 (/Users/diegof/.config/coc/extensions/node_modules/coc-stylua/lib/index.js:5885:12)
    at Promise2._settlePromises (/Users/diegof/.config/coc/extensions/node_modules/coc-stylua/lib/index.js:5953:16)
    at Async._drainQueue (/Users/diegof/.config/coc/extensions/node_modules/coc-stylua/lib/index.js:1906:12)
    at Async._drainQueues (/Users/diegof/.config/coc/extensions/node_modules/coc-stylua/lib/index.js:1915:10)
    at Async.drainQueues (/Users/diegof/.config/coc/extensions/node_modules/coc-stylua/lib/index.js:1803:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5))
```

I performed a quick investigation.
It seems that trying to download the binary from `download.fastgit.org` hits a Cloudflare DoS page and `unzipper` errors out.
That doesn't happen when I trigger the same request against `github.com`.
I assume that is related to the location from where I am executing the request?

I got around the problem by manually installing stylua binaries and using the `stylua.styluaPath` COC setting.
Is there a way to prevent this issue? Maybe adding a `stylua.downloadMirror` setting?

Thanks

**Comment by Tolomeo** [comment]
Also, notice I am asked to download the latest Stylua version even if I am using `stylua.styluaPath` option

**Comment by kgnugur** [comment]
The same thing happened to me, came here for the solution. Any possible updates?

**Comment by xiyaowong** [comment]
I'll refactor the code in a few days.
